In [19]:
import numpy as np
import pythreejs as p3
from IPython.display import display
from time import sleep

# Ball properties
NUM_BALLS = 10
RADIUS = 2
SPEED = 1
BOUNDARY = 50

# Create a scene
scene = p3.Scene(children=[
    p3.AmbientLight(color='#777777')
])
camera = p3.PerspectiveCamera(position=[0, 0, 100], aspect=1.6)
camera.lookAt([0, 0, 0])
renderer = p3.Renderer(camera=camera, scene=scene, controls=[p3.OrbitControls(controlling=camera)], width=800, height=600)

# Create ball meshes
ball_material = p3.MeshLambertMaterial(color='blue')
balls = []
for _ in range(NUM_BALLS):
    ball_geometry = p3.SphereGeometry(radius=RADIUS)
    ball = p3.Mesh(geometry=ball_geometry, material=ball_material)
    ball.position = [np.random.uniform(-BOUNDARY, BOUNDARY),
                              np.random.uniform(-BOUNDARY, BOUNDARY),
                              np.random.uniform(-BOUNDARY, BOUNDARY)]
    balls.append(ball)
    scene.add(ball)

# Create a cube to represent the boundary
cube_geometry = p3.BoxGeometry(width=BOUNDARY*2, height=BOUNDARY*2, depth=BOUNDARY*2)
cube_material = p3.MeshBasicMaterial(color='gray', wireframe=True)
cube = p3.Mesh(geometry=cube_geometry, material=cube_material)
scene.add(cube)

# Initial velocities
velocities = np.random.uniform(-SPEED, SPEED, (NUM_BALLS, 3))

def update_positions():
    for i, ball in enumerate(balls):
        ball.position = tuple(velocities[i])
        
        # Check for collisions with walls
        for j in range(3):
            if abs(ball.position[j]) + RADIUS > BOUNDARY:
                velocities[i][j] *= -1

        # Check for collisions with other balls
        for j in range(i + 1, NUM_BALLS):
            delta_pos = np.array(balls[j].position) - np.array(ball.position)
            distance = np.linalg.norm(delta_pos)
            if distance < 2 * RADIUS:
                norm_delta_pos = delta_pos / distance
                relative_velocity = velocities[i] - velocities[j]
                velocity_along_normal = np.dot(relative_velocity, norm_delta_pos)
                if velocity_along_normal > 0:
                    continue
                impulse = -2 * velocity_along_normal * norm_delta_pos
                velocities[i] += impulse
                velocities[j] -= impulse

display(renderer)

# Animation loop
while True:
    update_positions()
    renderer.render(scene, camera)
    sleep(0.05)


Renderer(camera=PerspectiveCamera(aspect=1.6, position=(0.0, 0.0, 100.0), projectionMatrix=(1.0, 0.0, 0.0, 0.0…

KeyboardInterrupt: 

In [4]:
velocities[1]

array([-0.87731843,  0.02592656,  0.17127367])

In [7]:
velocities

(array([ 0.01142889, -0.76032327, -0.1065297 ]),
 array([0.10449119, 0.03820757, 0.09255654]),
 array([ 0.96844162,  0.214225  , -0.85891881]),
 array([-0.2847956 ,  0.990812  , -0.01707052]),
 array([ 0.77526327,  0.66213105, -0.16647388]),
 array([-0.45710887,  0.51736731, -0.06730485]),
 array([ 0.36040739,  0.25923903, -0.92317259]),
 array([ 0.75148476, -0.93040712,  0.23600169]),
 array([-0.97982679,  0.59029876,  0.37652544]),
 array([ 0.59059236, -0.13378765, -0.65837247]))

In [13]:
tuple(velocities[9])

(0.5905923596954408, -0.133787654982654, -0.658372474475613)