In [147]:
import numpy as np

a  = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("a\n",a)

b = np.array([[4,6,5],[9,8,7],[7,5,3]])
print("b\n",b)



i = 0
j=0
prod_ab=np.empty([3,3])

for j in range(a.shape[0]):

  c = np.zeros([1,3],int)
  for i in range(b.shape[1]):
    c += (a[:,i]) * b[i,j]

  prod_ab[:,j] = c

print("AxB\n",prod_ab)


print("np.dot(a,b)\n",np.dot(a,b))



a
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
b
 [[4 6 5]
 [9 8 7]
 [7 5 3]]
AxB
 [[ 43.  37.  28.]
 [103.  94.  73.]
 [163. 151. 118.]]
np.dot(a,b)
 [[ 43  37  28]
 [103  94  73]
 [163 151 118]]


362880
